name=mysql-jdbc-connector
connector.class=io.confluent.connect.jdbc.JdbcSourceConnector
tasks.max=1
connection.url=jdbc:mysql://localhost:3306/users?user=root&password=root
mode=timestamp+incrementing
timestamp.column.name=last_updated
incrementing.column.name=id
topic.prefi x=users-
table.whitelist=users.user_profiles