version: '3.7'

services:
  artifactory:
    image: releases-docker.jfrog.io/jfrog/artifactory-oss:7.30.2
    container_name: artifactory-oss
    ports:
      - "8081:8081"
      - "8082:8082"
    environment:
      - EXTRA_JAVA_OPTIONS=-Xms512m -Xmx2g
    volumes:
      - artifactory_data:/var/opt/jfrog/artifactory
    restart: unless-stopped

volumes:
  artifactory_data:
