version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # disable security for dev
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - path.repo=/usr/share/elasticsearch/snapshots
    volumes:
      - ./es-snapshots:/usr/share/elasticsearch/snapshots
    ports:
      - "9200:9200"
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.0
    container_name: logstash
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./input-data:/usr/share/logstash/input-data
    ports:
      - "5044:5044"  # for beats
      - "9600:9600"  # monitoring
    networks:
      - elk
  apm-server:
    image: elastic/apm-server:7.10.2
    container_name: apm-server
    ports:
      - "8200:8200"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - KIBANA_HOST=http://kibana:5601
      - apm-server.host=0.0.0.0:8200
      - apm-server.shutdown_timeout=5s
      - xpack.security.enabled=false
    command: >
      apm-server -e
        -E apm-server.rum.enabled=true
        -E setup.kibana.host=kibana:5601
        -E setup.template.enabled=true
        -E output.elasticsearch.hosts=["elasticsearch:9200"]
    depends_on:
      - elasticsearch
      - kibana
    networks:
      - elk
networks:
  elk:
    driver: bridge
